config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :annual_state_crime_rates

  post 'range_year_crime', to: 'annual_state_crime_rates#range_year_crime'

  resources :years
  get 'animate_year', to: 'years#animate_year', as: :animate_year

  resources :crimes

  resources :states

  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  get '/comments/show', to: 'comments#show'
  get '/comments/hide', to: 'comments#hide'
  get '/comments/last_submitted', to: 'comments#last_submitted', as: :last_submitted
  get '/comments/cancel', to: 'comments#cancel', as: :comment_cancel
  resources :users, :only => [:index, :show, :update]

end

app/models/annual_state_crime_rate.rb
class AnnualStateCrimeRate < ActiveRecord::Base
  belongs_to :state
  belongs_to :year
  belongs_to :crime
  has_many :states
  has_many :years
  has_many :crimes

  def self.range_for_crime(id)
    rate_records = self.all.where(crime_id: id)
    rate_records.map {|record| record.rate}
  end

  def self.rates_for_year_and_crime(year_id, crime_id)
    year_raw_data = AnnualStateCrimeRate.all.where(year_id: Year.find_by(year: year_id.to_i).id, crime_id: crime_id)
    array = year_raw_data.map {|item| [item.state.abbr, item.rate]}
    array.sort_by!{|s,r|r}.reverse!
    array.each_with_index.map {|item, index| item.push(index)}
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_tree order: 'created_at DESC'
  belongs_to :user

  validates_presence_of :body

  def self.flatten_nested_hash(hash)
    hash.flat_map{|k, v| [k, *flatten_nested_hash(v)]}
  end
end

app/models/crime.rb
class Crime < ActiveRecord::Base
  has_many :annual_state_crime_rates
  has_many :states, through: :annual_state_crime_rates
  has_many :years, through: :annual_state_crime_rates
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :users
  has_many :annual_state_crime_rates
  has_many :years, through: :annual_state_crime_rates
  has_many :crimes, through: :annual_state_crime_rates
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable
  validates_presence_of :password_confirmation, :if => :password

  validates :username,
    :presence => true,
    :uniqueness => {
      :case_sensitive => false
    }

  belongs_to :state
  has_many :comments
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :annual_state_crime_rates
  has_many :states, through: :annual_state_crime_rates
  has_many :crimes, through: :annual_state_crime_rates
end

app/controllers/annual_state_crime_rates_controller.rb
class AnnualStateCrimeRatesController < ApplicationController
  def index
  end

  def range_year_crime #This should be refactored into the database or a rake task.
    range = AnnualStateCrimeRate.range_for_crime(params["crime"])
    @minimums = range.min
    @maximums = range.max
    @states = AnnualStateCrimeRate.rates_for_year_and_crime(params["form_year"], params["crime"]).to_json.html_safe
    @crimes = Crime.all
    respond_to do |format|  
      format.js {render 'home/index'}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :js

  def index
    @comments = Comment.hash_tree
  end

  def new
    if current_user
      @user_id = current_user.id
      @comment = Comment.new(parent_id: params[:parent_id])
      render :comment_new
    else
      render :comment_log_in_required
    end
  end

  def hide
    render :comment_hide
  end

  def show
    @comments = Comment.flatten_nested_hash(Comment.hash_tree)
    render :comment_show
  end

  def create

    if params[:comment][:parent_id].to_i > 0
      parent = Comment.find_by_id(params[:comment][:parent_id])
      @comment = parent.children.build(comment_params)
    else
      @comment = Comment.new(comment_params)
    end

    if @comment.save
      @comments = Comment.all
      @last_comment = Comment.all.where(user_id: current_user.id).last
      render :comment_last
    else
      render 'new'
    end
  end

  def cancel
    render :comment_cancel
  end


  private

    def comment_params
      params.require(:comment).permit(:title, :body, :user_id, :crime_id, :year_id)
    end

end

app/controllers/crimes_controller.rb
class CrimesController < ApplicationController
  


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @crimes = Crime.all

    @comment = Comment.new

    @comments = Comment.all
  end

end

app/controllers/states_controller.rb
class StatesController < ApplicationController
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @states = State.all
    @comments = Comment.all.where(user_id: current_user.id)
  end

  def update
    @user = User.find params[:id]
    @user.update(user_params)
    redirect_to user_path
  end

  private

   def user_params
      params.require(:user).permit(:state_id)
   end
end

app/controllers/years_controller.rb
class YearsController < ApplicationController

end

app/helpers/annual_state_crime_rates_helper.rb
module AnnualStateCrimeRatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for(comments)
    comments.map do |comment, nested_comments|
      render(comment) +
          (nested_comments.size > 0 ? content_tag(:div, comments_tree_for(nested_comments), class: "replies") : nil)
    end.join.html_safe
  end
end

app/helpers/crimes_helper.rb
module CrimesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/comments/_comment.html.erb
<% if !!comment.parent_id %>
  <div class="well replies" id='id-<%=j "#{comment.id}"%>'>
<% else %> <div class="well" id='id-<%=j "#{comment.id}"%>'>
<% end %>
  <h2><%= comment.title %></h2>
  <p class="text-muted">Added by <strong><%= comment.author %></strong> on
    <%= l(comment.created_at, format: '%B, %d %Y %H:%M:%S') %></p>

    <p><%= comment.body %></p>

  <% from_reply_form ||= nil %>
  <% unless from_reply_form %>
    <% if comment.leaf? && comment.parent_id == nil %>
      <small class="text-muted">There are no replies yet - be the first one to reply!</small>
    <% end %>
    <% unless comment.parent_id %>
    <p><%= link_to 'reply', new_comment_path(comment.id), class: 'reply_link', remote: true %></p>
    <% end %>
  <% end %>
</div> 

app/views/comments/_comment_form.html.erb
<%= form_for(@comment, remote: true) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<% if @comment.parent_id == nil %>
  <div class="form-group">
     <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
<% end %>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', required: true %>
  </div>

  <%= f.hidden_field :user_id, value: @user_id %>
  <%= f.hidden_field :parent_id, value: @comment.parent_id %>
  <%= f.submit class: 'btn btn-primary', value: "Submit" %>
  <%= link_to 'Cancel', comment_cancel_path, remote: true, class: 'btn btn-danger', id: 'cancel_comment' %>
<% end %>

app/views/comments/_new_comment.html.erb
<h1>New comment</h1>

<% if @comment.parent %>
  <%= render 'comment', comment: @comment.parent, from_reply_form: true %>
<% end %>

<%= render 'comment_form' %>

app/views/comments/comment_cancel.js.erb
$(".comment-div").empty();
$('#hide-comments').hide();
$('#show-comments').show();
$("#add-comment").show();

app/views/comments/comment_hide.js.erb
$("#show-comments").show();
$("#hide-comments").hide();
$("#add-comment").show();
$("html, body").animate({
     scrollTop: 0
 }, 2000);
$(".comment-div").children().fadeOut(1500, function(){
  $(".comment-div").empty();
});

app/views/comments/comment_last.js.erb
$("#add-comment").show();
$(".comment-div").empty()
$(".comment-div").append("<%= j render @comments %>");
$('html, body').animate({
    scrollTop: $("#id-<%=@last_comment.id %>").offset().top
}, 300);

app/views/comments/comment_log_in_required.js.erb
alert("You must log in to submit a comment.")

app/views/comments/comment_new.js.erb
$("#add-comment").hide()
$(".reply_link").hide();
<% if @comment.parent_id %>
  $("#id-<%= j @comment.parent_id.to_json %>").append("<%= j render "comment_form" %>");
<% else %>
  $(".comment-div").empty();
  $(".comment-div").prepend("<%= j render "comment_form" %>");
<% end %>
$('html, body').animate({
    scrollTop: $("#comment_cancel").offset().top
}, 2000);

app/views/comments/comment_show.js.erb
$("#show-comments").toggle();
$("#hide-comments").toggle();
$("#add-comment").show();
$(".comment-div").append("<%= j render @comments %>")
$('html, body').animate({
    scrollTop: $(".comment-div").offset().top
}, 2000);

app/views/comments/new_comment.js.erb
$("#id-<%=@comment.parent_id%>").append("TESTTESTTEST");
alert('success')