config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :annual_state_crime_rates

  post 'range_year_crime', to: 'annual_state_crime_rates#range_year_crime'

  resources :years
  get 'animate_year', to: 'years#animate_year', as: :animate_year

  resources :crimes

  resources :states

  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  get '/comments/show', to: 'comments#show'
  get '/comments/hide', to: 'comments#hide'
  get '/comments/last_submitted', to: 'comments#last_submitted', as: :last_submitted
  get '/comments/cancel', to: 'comments#cancel', as: :comment_cancel
  resources :users, :only => [:index, :show, :update]

end

app/models/annual_state_crime_rate.rb
class AnnualStateCrimeRate < ActiveRecord::Base
  belongs_to :state
  belongs_to :year
  belongs_to :crime
  has_many :states
  has_many :years
  has_many :crimes

  def self.range_for_crime(id)
    rate_records = self.all.where(crime_id: id)
    rate_records.map {|record| record.rate}
  end

  def self.rates_for_year_and_crime(year_id, crime_id)
    year_raw_data = AnnualStateCrimeRate.all.where(year_id: Year.find_by(year: year_id.to_i).id, crime_id: crime_id)
    array = year_raw_data.map {|item| [item.state.abbr, item.rate]}
    array.sort_by!{|s,r|r}.reverse!
    array.each_with_index.map {|item, index| item.push(index)}
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_tree order: 'created_at DESC'
  belongs_to :user

  validates_presence_of :body

  def self.flatten_nested_hash(hash)
    hash.flat_map{|k, v| [k, *flatten_nested_hash(v)]}
  end
end

app/models/crime.rb
class Crime < ActiveRecord::Base
  has_many :annual_state_crime_rates
  has_many :states, through: :annual_state_crime_rates
  has_many :years, through: :annual_state_crime_rates
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :users
  has_many :annual_state_crime_rates
  has_many :years, through: :annual_state_crime_rates
  has_many :crimes, through: :annual_state_crime_rates
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable
  validates_presence_of :password_confirmation, :if => :password

  validates :username,
    :presence => true,
    :uniqueness => {
      :case_sensitive => false
    }

  belongs_to :state
  has_many :comments
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :annual_state_crime_rates
  has_many :states, through: :annual_state_crime_rates
  has_many :crimes, through: :annual_state_crime_rates
end

app/controllers/annual_state_crime_rates_controller.rb
class AnnualStateCrimeRatesController < ApplicationController
  def index
  end

  def range_year_crime #This should be refactored into the database or a rake task.
    range = AnnualStateCrimeRate.range_for_crime(params["crime"])
    @minimums = range.min
    @maximums = range.max
    @states = AnnualStateCrimeRate.rates_for_year_and_crime(params["form_year"], params["crime"]).to_json.html_safe
    @crimes = Crime.all
    respond_to do |format|  
      format.js {render 'home/index'}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :js

  def index
    @comments = Comment.hash_tree
  end

  def new
    if current_user
      @user_id = current_user.id
      @comment = Comment.new(parent_id: params[:parent_id])
      render :comment_new
    else
      render :comment_log_in_required
    end
  end

  def hide
    render :comment_hide
  end

  def show
    @comments = Comment.flatten_nested_hash(Comment.hash_tree)
    render :comment_show
  end

  def create

    if params[:comment][:parent_id].to_i > 0
      parent = Comment.find_by_id(params[:comment][:parent_id])
      @comment = parent.children.build(comment_params)
    else
      @comment = Comment.new(comment_params)
    end

    if @comment.save
      @comments = Comment.all
      @last_comment = Comment.all.where(user_id: current_user.id).last
      render :comment_last
    else
      render 'new'
    end
  end

  def cancel
    render :comment_cancel
  end


  private

    def comment_params
      params.require(:comment).permit(:title, :body, :user_id, :crime_id, :year_id)
    end

end

app/controllers/crimes_controller.rb
class CrimesController < ApplicationController
  


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @crimes = Crime.all

    @comment = Comment.new

    @comments = Comment.all
  end

end

app/controllers/states_controller.rb
class StatesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @states = State.all
    @comments = Comment.all.where(user_id: current_user.id)
  end

  def update
    @user = User.find params[:id]
    @user.update(user_params)
    redirect_to user_path
  end

  private

   def user_params
      params.require(:user).permit(:state_id)
   end
end

app/controllers/years_controller.rb
class YearsController < ApplicationController

end

app/helpers/annual_state_crime_rates_helper.rb
module AnnualStateCrimeRatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for(comments)
    comments.map do |comment, nested_comments|
      render(comment) +
          (nested_comments.size > 0 ? content_tag(:div, comments_tree_for(nested_comments), class: "replies") : nil)
    end.join.html_safe
  end
end

app/helpers/crimes_helper.rb
module CrimesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/home/_crime_rate_form.html.erb
<%= form_tag("/range_year_crime", id: "crime_form", method: "post", remote: true) do %>

  <%= select_tag "crime", options_from_collection_for_select(@crimes, "id", "name"), class: "form-control" %>

  <br>
  <%= hidden_field_tag 'form_year', value=1965 %>
  <%= submit_tag("Submit Crime", type: "hidden") %>
<% end %>

app/views/home/_form.html.erb
<%= form_tag("/range_year_crime", id: "crime_form", method: "post", remote: true) do %>

  <%= select_tag "crime", options_from_collection_for_select(@crimes, "id", "name") %>

  <br>
  <%= hidden_field_tag 'form_year', value=1965 %>
  <%= submit_tag("Submit Crime") %>
<% end %>

app/views/home/_login.html.erb
  <% if user_signed_in? %>
    <div class="login">
      Logged in as <strong><%= current_user.username %></strong><br>
      <%= link_to 'Edit profile | ', edit_user_registration_path %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    </div>
  <% else %>
    <div class="login">
      <%= link_to "Sign Up | ", new_user_registration_path %>
      <%= link_to "Login", new_user_session_path %>
    </div>
  <% end %>
</div>

app/views/home/_map.html.erb
<div class="col-xs-12" id="map-container"></div>

app/views/home/_map_div.html.erb
<div id="container" style="position: relative; width: 85%; height: 85%;"></div>

app/views/home/index.html.erb
<div class="container" >
  <div class="jumbotron" id="jumbotron1">


    <div class="row">
      <div class="col-xs-12 col-md-2" >

        <%= render "home/crime_rate_form" %>
      </div>

      <div class="col-x-1 col-md-1"><%= link_to 'Play', animate_year_path, remote: true, class: 'btn btn-primary btn-md', id: 'play-button' %></div>

      <div class="container col-xs-11 col-md-9" style="position: relative; width: 75%;">


        <!-- <label for="year">Year</label> -->
        <input type="range" min="1965" max="2012" value="1965" id="fader" step="1" oninput="outputUpdate(value)">
        <!-- <output for="fader" id="year">1965</output> -->
      </div>
      <div class="col-xs-3"></div><output class="col-xs-6" for="fader" id="year">1965</output><div class="col-xs-3">
    </div>

    <div class="row">
        <div class="col-xs-12" id="map-container"></div>
        <!-- <div class="col-xs-2"></div> -->
    </div>

    <div class="container-fluid legend">
      <div class="row">
        <div class="col-xs-3"></div><div class="col-xs-6 text-left" id="legend_name"></div><div class="col-xs-3"></div>
      </div>
      <div class="row">
        <div class="col-xs-3"></div>
        <canvas class="col-xs-6" id="myCanvas" width="500" height="25"></canvas>
        <div class="col-xs-3"></div>
      </div>
      <div class="row">
        <div class="col-xs-3"></div><div class="col-xs-3 text-left" id="min_legend"></div>
        <div class="col-xs-3 text-right" id="max_legend"></div><div class="col-xs-3"></div>
      </div>
    </div>

  </div>
</div>

<div class="jumbotron" id="jumbotron2">
  <div class="container">
    <h3>Join the discussion</h3>
    <p id="comment-buttons">
      <%= link_to 'Show Comments',  comments_show_path, remote: true, class: 'btn btn-primary btn-lg', id: 'show-comments' %>
      <%= link_to 'Hide Comments',  comments_hide_path, remote: true, class: 'btn btn-primary btn-lg', id: 'hide-comments' %>
      <%= link_to 'Add Comment', new_comment_path, remote: true, class: 'btn btn-primary btn-lg', id: 'add-comment' %>
    </p>
  </div>
</div>

<div class="comment-div"></div>

app/views/home/index.js.erb
$("#map-container").empty();

var minimums =  <%= @minimums %>;
var maximums =  <%= @maximums %>;
var states = <%= @states %>;
var legend_crime = $("#crime :selected").text()

rawData(minimums, maximums, states);

$("#min_legend").text(minimums/10 + " per 100,000")
$("#max_legend").text(maximums/10 + " per 100,000")
$("#legend_name").text(legend_crime)